# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AuthorizeRequestPb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AuthorizeRequestPb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n\x18\x41uthorizeRequestPb.proto\"\x87\x01\n\x12\x41uthorizeRequestPb\x12\x13\n\x0b\x61\x63\x63ountName\x18\x01 \x01(\t\x12\x14\n\x0cuserPassWord\x18\x02 \x01(\t\x12\x16\n\x0eorganizationID\x18\x03 \x01(\t\x12\x19\n\x11observationDeptID\x18\x04 \x01(\t\x12\x13\n\x0buseScenario\x18\x05 \x01(\tB\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
)




_AUTHORIZEREQUESTPB = _descriptor.Descriptor(
  name='AuthorizeRequestPb',
  full_name='AuthorizeRequestPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accountName', full_name='AuthorizeRequestPb.accountName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userPassWord', full_name='AuthorizeRequestPb.userPassWord', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='organizationID', full_name='AuthorizeRequestPb.organizationID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observationDeptID', full_name='AuthorizeRequestPb.observationDeptID', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='useScenario', full_name='AuthorizeRequestPb.useScenario', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=164,
)

DESCRIPTOR.message_types_by_name['AuthorizeRequestPb'] = _AUTHORIZEREQUESTPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuthorizeRequestPb = _reflection.GeneratedProtocolMessageType('AuthorizeRequestPb', (_message.Message,), {
  'DESCRIPTOR' : _AUTHORIZEREQUESTPB,
  '__module__' : 'AuthorizeRequestPb_pb2'
  # @@protoc_insertion_point(class_scope:AuthorizeRequestPb)
  })
_sym_db.RegisterMessage(AuthorizeRequestPb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
