# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CacheListResponsePb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import login.proto_pb.DictionaryDetailResponsePb_pb2 as DictionaryDetailResponsePb__pb2
import login.proto_pb.UserResponsePb_pb2 as UserResponsePb__pb2
import login.proto_pb.ServiceSectResponsePb_pb2 as ServiceSectResponsePb__pb2
import login.proto_pb.ExamBodyPartResponsePb_pb2 as ExamBodyPartResponsePb__pb2
import login.proto_pb.ProcedureResponsePb_pb2 as ProcedureResponsePb__pb2
import login.proto_pb.ObservationLocationResponsePb_pb2 as ObservationLocationResponsePb__pb2
import login.proto_pb.OrganizationResponsePb_pb2 as OrganizationResponsePb__pb2
import login.proto_pb.ObservationDeptResponsePb_pb2 as ObservationDeptResponsePb__pb2
import login.proto_pb.ProviderDoctorResponsePb_pb2 as ProviderDoctorResponsePb__pb2
import login.proto_pb.PatientClassResponsePb_pb2 as PatientClassResponsePb__pb2
import login.proto_pb.QuickInputCodeResponsePb_pb2 as QuickInputCodeResponsePb__pb2
import login.proto_pb.WebParamResponsePb_pb2 as WebParamResponsePb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='CacheListResponsePb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n\x19\x43\x61\x63heListResponsePb.proto\x1a DictionaryDetailResponsePb.proto\x1a\x14UserResponsePb.proto\x1a\x1bServiceSectResponsePb.proto\x1a\x1c\x45xamBodyPartResponsePb.proto\x1a\x19ProcedureResponsePb.proto\x1a#ObservationLocationResponsePb.proto\x1a\x1cOrganizationResponsePb.proto\x1a\x1fObservationDeptResponsePb.proto\x1a\x1eProviderDoctorResponsePb.proto\x1a\x1cPatientClassResponsePb.proto\x1a\x1eQuickInputCodeResponsePb.proto\x1a\x18WebParamResponsePb.proto\"\xcb\x04\n\x13\x43\x61\x63heListResponsePb\x12\x35\n\x10\x64ictionaryDetail\x18\x01 \x03(\x0b\x32\x1b.DictionaryDetailResponsePb\x12\x1d\n\x04user\x18\x02 \x03(\x0b\x32\x0f.UserResponsePb\x12+\n\x0bserviceSect\x18\x03 \x03(\x0b\x32\x16.ServiceSectResponsePb\x12-\n\x0c\x65xamBodyPart\x18\x04 \x03(\x0b\x32\x17.ExamBodyPartResponsePb\x12\'\n\tprocedure\x18\x05 \x03(\x0b\x32\x14.ProcedureResponsePb\x12;\n\x13observationLocation\x18\x06 \x03(\x0b\x32\x1e.ObservationLocationResponsePb\x12-\n\x0corganization\x18\x07 \x03(\x0b\x32\x17.OrganizationResponsePb\x12\x33\n\x0fobservationDept\x18\x08 \x03(\x0b\x32\x1a.ObservationDeptResponsePb\x12\x31\n\x0eproviderDoctor\x18\t \x03(\x0b\x32\x19.ProviderDoctorResponsePb\x12-\n\x0cpatientClass\x18\n \x03(\x0b\x32\x17.PatientClassResponsePb\x12\x31\n\x0equickInputCode\x18\x0b \x03(\x0b\x32\x19.QuickInputCodeResponsePb\x12#\n\x06params\x18\x0c \x03(\x0b\x32\x13.WebParamResponsePbB\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
  ,
  dependencies=[DictionaryDetailResponsePb__pb2.DESCRIPTOR,UserResponsePb__pb2.DESCRIPTOR,ServiceSectResponsePb__pb2.DESCRIPTOR,ExamBodyPartResponsePb__pb2.DESCRIPTOR,ProcedureResponsePb__pb2.DESCRIPTOR,ObservationLocationResponsePb__pb2.DESCRIPTOR,OrganizationResponsePb__pb2.DESCRIPTOR,ObservationDeptResponsePb__pb2.DESCRIPTOR,ProviderDoctorResponsePb__pb2.DESCRIPTOR,PatientClassResponsePb__pb2.DESCRIPTOR,QuickInputCodeResponsePb__pb2.DESCRIPTOR,WebParamResponsePb__pb2.DESCRIPTOR,])




_CACHELISTRESPONSEPB = _descriptor.Descriptor(
  name='CacheListResponsePb',
  full_name='CacheListResponsePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dictionaryDetail', full_name='CacheListResponsePb.dictionaryDetail', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='CacheListResponsePb.user', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serviceSect', full_name='CacheListResponsePb.serviceSect', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='examBodyPart', full_name='CacheListResponsePb.examBodyPart', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='procedure', full_name='CacheListResponsePb.procedure', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observationLocation', full_name='CacheListResponsePb.observationLocation', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='organization', full_name='CacheListResponsePb.organization', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observationDept', full_name='CacheListResponsePb.observationDept', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='providerDoctor', full_name='CacheListResponsePb.providerDoctor', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='patientClass', full_name='CacheListResponsePb.patientClass', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quickInputCode', full_name='CacheListResponsePb.quickInputCode', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='CacheListResponsePb.params', index=11,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=979,
)

_CACHELISTRESPONSEPB.fields_by_name['dictionaryDetail'].message_type = DictionaryDetailResponsePb__pb2._DICTIONARYDETAILRESPONSEPB
_CACHELISTRESPONSEPB.fields_by_name['user'].message_type = UserResponsePb__pb2._USERRESPONSEPB
_CACHELISTRESPONSEPB.fields_by_name['serviceSect'].message_type = ServiceSectResponsePb__pb2._SERVICESECTRESPONSEPB
_CACHELISTRESPONSEPB.fields_by_name['examBodyPart'].message_type = ExamBodyPartResponsePb__pb2._EXAMBODYPARTRESPONSEPB
_CACHELISTRESPONSEPB.fields_by_name['procedure'].message_type = ProcedureResponsePb__pb2._PROCEDURERESPONSEPB
_CACHELISTRESPONSEPB.fields_by_name['observationLocation'].message_type = ObservationLocationResponsePb__pb2._OBSERVATIONLOCATIONRESPONSEPB
_CACHELISTRESPONSEPB.fields_by_name['organization'].message_type = OrganizationResponsePb__pb2._ORGANIZATIONRESPONSEPB
_CACHELISTRESPONSEPB.fields_by_name['observationDept'].message_type = ObservationDeptResponsePb__pb2._OBSERVATIONDEPTRESPONSEPB
_CACHELISTRESPONSEPB.fields_by_name['providerDoctor'].message_type = ProviderDoctorResponsePb__pb2._PROVIDERDOCTORRESPONSEPB
_CACHELISTRESPONSEPB.fields_by_name['patientClass'].message_type = PatientClassResponsePb__pb2._PATIENTCLASSRESPONSEPB
_CACHELISTRESPONSEPB.fields_by_name['quickInputCode'].message_type = QuickInputCodeResponsePb__pb2._QUICKINPUTCODERESPONSEPB
_CACHELISTRESPONSEPB.fields_by_name['params'].message_type = WebParamResponsePb__pb2._WEBPARAMRESPONSEPB
DESCRIPTOR.message_types_by_name['CacheListResponsePb'] = _CACHELISTRESPONSEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CacheListResponsePb = _reflection.GeneratedProtocolMessageType('CacheListResponsePb', (_message.Message,), {
  'DESCRIPTOR' : _CACHELISTRESPONSEPB,
  '__module__' : 'CacheListResponsePb_pb2'
  # @@protoc_insertion_point(class_scope:CacheListResponsePb)
  })
_sym_db.RegisterMessage(CacheListResponsePb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
