# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DictionaryDetailResponsePb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DictionaryDetailResponsePb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n DictionaryDetailResponsePb.proto\"\xa0\x02\n\x1a\x44ictionaryDetailResponsePb\x12\x13\n\x0b\x64icDetailID\x18\x01 \x01(\t\x12\x13\n\x0b\x64icCategory\x18\x02 \x01(\t\x12\x14\n\x0c\x64icInPutCode\x18\x03 \x01(\t\x12\x0f\n\x07\x64icCode\x18\x04 \x01(\t\x12\x17\n\x0f\x64icDisplayValue\x18\x05 \x01(\t\x12\x19\n\x11\x64icMappingHISCode\x18\x06 \x01(\t\x12\x19\n\x11observationDeptID\x18\x07 \x01(\t\x12\x16\n\x0eorganizationID\x18\x08 \x01(\t\x12\x0e\n\x06sortNo\x18\t \x01(\x05\x12\x0e\n\x06remark\x18\n \x01(\t\x12\x13\n\x0b\x64\x65letedFlag\x18\x0b \x01(\x08\x12\x15\n\rdeletedFlagCH\x18\x0c \x01(\tB\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
)




_DICTIONARYDETAILRESPONSEPB = _descriptor.Descriptor(
  name='DictionaryDetailResponsePb',
  full_name='DictionaryDetailResponsePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dicDetailID', full_name='DictionaryDetailResponsePb.dicDetailID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dicCategory', full_name='DictionaryDetailResponsePb.dicCategory', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dicInPutCode', full_name='DictionaryDetailResponsePb.dicInPutCode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dicCode', full_name='DictionaryDetailResponsePb.dicCode', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dicDisplayValue', full_name='DictionaryDetailResponsePb.dicDisplayValue', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dicMappingHISCode', full_name='DictionaryDetailResponsePb.dicMappingHISCode', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observationDeptID', full_name='DictionaryDetailResponsePb.observationDeptID', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='organizationID', full_name='DictionaryDetailResponsePb.organizationID', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sortNo', full_name='DictionaryDetailResponsePb.sortNo', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remark', full_name='DictionaryDetailResponsePb.remark', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deletedFlag', full_name='DictionaryDetailResponsePb.deletedFlag', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deletedFlagCH', full_name='DictionaryDetailResponsePb.deletedFlagCH', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=325,
)

DESCRIPTOR.message_types_by_name['DictionaryDetailResponsePb'] = _DICTIONARYDETAILRESPONSEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DictionaryDetailResponsePb = _reflection.GeneratedProtocolMessageType('DictionaryDetailResponsePb', (_message.Message,), {
  'DESCRIPTOR' : _DICTIONARYDETAILRESPONSEPB,
  '__module__' : 'DictionaryDetailResponsePb_pb2'
  # @@protoc_insertion_point(class_scope:DictionaryDetailResponsePb)
  })
_sym_db.RegisterMessage(DictionaryDetailResponsePb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
