# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ObservationDeptResponsePb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ObservationDeptResponsePb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n\x1fObservationDeptResponsePb.proto\"\xa5\x02\n\x19ObservationDeptResponsePb\x12\x19\n\x11observationDeptID\x18\x01 \x01(\t\x12\x10\n\x08\x64\x65ptCode\x18\x02 \x01(\t\x12\x10\n\x08\x64\x65ptName\x18\x03 \x01(\t\x12\x10\n\x08\x64\x65ptType\x18\x04 \x01(\t\x12\x12\n\ndeptTypeCH\x18\x05 \x01(\t\x12\x12\n\nxADeptFlag\x18\x06 \x01(\x08\x12\x14\n\x0cxADeptFlagCH\x18\x07 \x01(\t\x12\x13\n\x0b\x64\x65letedFlag\x18\x08 \x01(\x08\x12\x15\n\rdeletedFlagCH\x18\t \x01(\t\x12\x16\n\x0eorganizationID\x18\n \x01(\t\x12\x0e\n\x06sortNo\x18\x0b \x01(\x05\x12\x13\n\x0b\x63urrentPage\x18\x0c \x01(\x05\x12\x10\n\x08pageSize\x18\r \x01(\x05\x42\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
)




_OBSERVATIONDEPTRESPONSEPB = _descriptor.Descriptor(
  name='ObservationDeptResponsePb',
  full_name='ObservationDeptResponsePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='observationDeptID', full_name='ObservationDeptResponsePb.observationDeptID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deptCode', full_name='ObservationDeptResponsePb.deptCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deptName', full_name='ObservationDeptResponsePb.deptName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deptType', full_name='ObservationDeptResponsePb.deptType', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deptTypeCH', full_name='ObservationDeptResponsePb.deptTypeCH', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='xADeptFlag', full_name='ObservationDeptResponsePb.xADeptFlag', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='xADeptFlagCH', full_name='ObservationDeptResponsePb.xADeptFlagCH', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deletedFlag', full_name='ObservationDeptResponsePb.deletedFlag', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deletedFlagCH', full_name='ObservationDeptResponsePb.deletedFlagCH', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='organizationID', full_name='ObservationDeptResponsePb.organizationID', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sortNo', full_name='ObservationDeptResponsePb.sortNo', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currentPage', full_name='ObservationDeptResponsePb.currentPage', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='ObservationDeptResponsePb.pageSize', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=329,
)

DESCRIPTOR.message_types_by_name['ObservationDeptResponsePb'] = _OBSERVATIONDEPTRESPONSEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ObservationDeptResponsePb = _reflection.GeneratedProtocolMessageType('ObservationDeptResponsePb', (_message.Message,), {
  'DESCRIPTOR' : _OBSERVATIONDEPTRESPONSEPB,
  '__module__' : 'ObservationDeptResponsePb_pb2'
  # @@protoc_insertion_point(class_scope:ObservationDeptResponsePb)
  })
_sym_db.RegisterMessage(ObservationDeptResponsePb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
