# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OrganizationResponsePb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='OrganizationResponsePb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n\x1cOrganizationResponsePb.proto\"\xea\x03\n\x16OrganizationResponsePb\x12\x16\n\x0eorganizationID\x18\x01 \x01(\t\x12\x18\n\x10organizationCode\x18\x02 \x01(\t\x12\x1b\n\x13organizationHISCode\x18\x03 \x01(\t\x12\x18\n\x10organizationName\x18\x04 \x01(\t\x12\x17\n\x0forganizationEng\x18\x05 \x01(\t\x12\x13\n\x0bparentOrgID\x18\x06 \x01(\t\x12\x12\n\norgAddress\x18\x07 \x01(\t\x12\x14\n\x0corgTelephone\x18\x08 \x01(\t\x12\x13\n\x0borgFullName\x18\t \x01(\t\x12\x13\n\x0borgRootFlag\x18\n \x01(\x08\x12\x13\n\x0b\x64\x65letedFlag\x18\x0b \x01(\x08\x12\x15\n\rdeletedFlagCH\x18\x0c \x01(\t\x12\x1a\n\x12\x64iagnoseCenterFlag\x18\r \x01(\x08\x12\x1c\n\x14\x64iagnoseCenterFlagCH\x18\x0e \x01(\t\x12\x18\n\x10\x61ppServerAddress\x18\x0f \x01(\t\x12\x1a\n\x12\x64\x42\x43onnectionString\x18\x10 \x01(\t\x12\x0e\n\x06remark\x18\x11 \x01(\t\x12\x0e\n\x06sortNo\x18\x12 \x01(\x05\x12)\n\x08\x63hildren\x18\x13 \x03(\x0b\x32\x17.OrganizationResponsePbB\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
)




_ORGANIZATIONRESPONSEPB = _descriptor.Descriptor(
  name='OrganizationResponsePb',
  full_name='OrganizationResponsePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='organizationID', full_name='OrganizationResponsePb.organizationID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='organizationCode', full_name='OrganizationResponsePb.organizationCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='organizationHISCode', full_name='OrganizationResponsePb.organizationHISCode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='organizationName', full_name='OrganizationResponsePb.organizationName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='organizationEng', full_name='OrganizationResponsePb.organizationEng', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parentOrgID', full_name='OrganizationResponsePb.parentOrgID', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orgAddress', full_name='OrganizationResponsePb.orgAddress', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orgTelephone', full_name='OrganizationResponsePb.orgTelephone', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orgFullName', full_name='OrganizationResponsePb.orgFullName', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orgRootFlag', full_name='OrganizationResponsePb.orgRootFlag', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deletedFlag', full_name='OrganizationResponsePb.deletedFlag', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deletedFlagCH', full_name='OrganizationResponsePb.deletedFlagCH', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='diagnoseCenterFlag', full_name='OrganizationResponsePb.diagnoseCenterFlag', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='diagnoseCenterFlagCH', full_name='OrganizationResponsePb.diagnoseCenterFlagCH', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='appServerAddress', full_name='OrganizationResponsePb.appServerAddress', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dBConnectionString', full_name='OrganizationResponsePb.dBConnectionString', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remark', full_name='OrganizationResponsePb.remark', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sortNo', full_name='OrganizationResponsePb.sortNo', index=17,
      number=18, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='children', full_name='OrganizationResponsePb.children', index=18,
      number=19, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=523,
)

_ORGANIZATIONRESPONSEPB.fields_by_name['children'].message_type = _ORGANIZATIONRESPONSEPB
DESCRIPTOR.message_types_by_name['OrganizationResponsePb'] = _ORGANIZATIONRESPONSEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrganizationResponsePb = _reflection.GeneratedProtocolMessageType('OrganizationResponsePb', (_message.Message,), {
  'DESCRIPTOR' : _ORGANIZATIONRESPONSEPB,
  '__module__' : 'OrganizationResponsePb_pb2'
  # @@protoc_insertion_point(class_scope:OrganizationResponsePb)
  })
_sym_db.RegisterMessage(OrganizationResponsePb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
