# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProviderDoctorResponsePb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProviderDoctorResponsePb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n\x1eProviderDoctorResponsePb.proto\"\xe2\x02\n\x18ProviderDoctorResponsePb\x12\x12\n\nproviderID\x18\x01 \x01(\t\x12\x14\n\x0cproviderName\x18\x02 \x01(\t\x12\x14\n\x0cproviderCode\x18\x03 \x01(\t\x12\x0b\n\x03sex\x18\x04 \x01(\t\x12\r\n\x05sexCH\x18\x05 \x01(\t\x12\x10\n\x08\x62irthDay\x18\x06 \x01(\t\x12\x0c\n\x04\x64uty\x18\x07 \x01(\t\x12\x13\n\x0bofficePhone\x18\x08 \x01(\t\x12\x11\n\ttelephone\x18\t \x01(\t\x12\r\n\x05\x65mail\x18\n \x01(\t\x12\x0e\n\x06iDCard\x18\x0b \x01(\t\x12\x12\n\nspeciality\x18\x0c \x01(\t\x12\x19\n\x11observationDeptID\x18\r \x01(\t\x12\x16\n\x0eorganizationID\x18\x0e \x01(\t\x12\x13\n\x0b\x64\x65letedFlag\x18\x0f \x01(\x08\x12\x0e\n\x06sortNo\x18\x10 \x01(\x05\x12\x17\n\x0fobservationDept\x18\x11 \x01(\tB\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
)




_PROVIDERDOCTORRESPONSEPB = _descriptor.Descriptor(
  name='ProviderDoctorResponsePb',
  full_name='ProviderDoctorResponsePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='providerID', full_name='ProviderDoctorResponsePb.providerID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='providerName', full_name='ProviderDoctorResponsePb.providerName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='providerCode', full_name='ProviderDoctorResponsePb.providerCode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sex', full_name='ProviderDoctorResponsePb.sex', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sexCH', full_name='ProviderDoctorResponsePb.sexCH', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='birthDay', full_name='ProviderDoctorResponsePb.birthDay', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duty', full_name='ProviderDoctorResponsePb.duty', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='officePhone', full_name='ProviderDoctorResponsePb.officePhone', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='telephone', full_name='ProviderDoctorResponsePb.telephone', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='ProviderDoctorResponsePb.email', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iDCard', full_name='ProviderDoctorResponsePb.iDCard', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speciality', full_name='ProviderDoctorResponsePb.speciality', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observationDeptID', full_name='ProviderDoctorResponsePb.observationDeptID', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='organizationID', full_name='ProviderDoctorResponsePb.organizationID', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deletedFlag', full_name='ProviderDoctorResponsePb.deletedFlag', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sortNo', full_name='ProviderDoctorResponsePb.sortNo', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observationDept', full_name='ProviderDoctorResponsePb.observationDept', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=389,
)

DESCRIPTOR.message_types_by_name['ProviderDoctorResponsePb'] = _PROVIDERDOCTORRESPONSEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProviderDoctorResponsePb = _reflection.GeneratedProtocolMessageType('ProviderDoctorResponsePb', (_message.Message,), {
  'DESCRIPTOR' : _PROVIDERDOCTORRESPONSEPB,
  '__module__' : 'ProviderDoctorResponsePb_pb2'
  # @@protoc_insertion_point(class_scope:ProviderDoctorResponsePb)
  })
_sym_db.RegisterMessage(ProviderDoctorResponsePb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
