# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QuickInputCodeResponsePb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='QuickInputCodeResponsePb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n\x1eQuickInputCodeResponsePb.proto\"\x81\x03\n\x18QuickInputCodeResponsePb\x12\x0e\n\x06\x63odeID\x18\x01 \x01(\t\x12\x16\n\x0equickInputCode\x18\x02 \x01(\t\x12\x15\n\rserviceSectID\x18\x03 \x01(\t\x12\x16\n\x0e\x65xamBodyPartID\x18\x04 \x01(\t\x12\x13\n\x0bprocedureID\x18\x05 \x01(\t\x12\x1d\n\x15observationLocationID\x18\x06 \x01(\t\x12\x14\n\x0cpatientClass\x18\x07 \x01(\x05\x12\x18\n\x10patientClassName\x18\x08 \x01(\t\x12\x19\n\x11observationDeptID\x18\t \x01(\t\x12\x16\n\x0eorganizationID\x18\n \x01(\t\x12\x13\n\x0b\x64\x65letedFlag\x18\x0b \x01(\x08\x12\x14\n\x0c\x64\x65leteFlagCH\x18\x0c \x01(\t\x12\x15\n\rprocedureName\x18\r \x01(\t\x12\x18\n\x10\x65xamBodyPartName\x18\x0e \x01(\t\x12\x1b\n\x13observationLocation\x18\x0f \x01(\tB\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
)




_QUICKINPUTCODERESPONSEPB = _descriptor.Descriptor(
  name='QuickInputCodeResponsePb',
  full_name='QuickInputCodeResponsePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='codeID', full_name='QuickInputCodeResponsePb.codeID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quickInputCode', full_name='QuickInputCodeResponsePb.quickInputCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serviceSectID', full_name='QuickInputCodeResponsePb.serviceSectID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='examBodyPartID', full_name='QuickInputCodeResponsePb.examBodyPartID', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='procedureID', full_name='QuickInputCodeResponsePb.procedureID', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observationLocationID', full_name='QuickInputCodeResponsePb.observationLocationID', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='patientClass', full_name='QuickInputCodeResponsePb.patientClass', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='patientClassName', full_name='QuickInputCodeResponsePb.patientClassName', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observationDeptID', full_name='QuickInputCodeResponsePb.observationDeptID', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='organizationID', full_name='QuickInputCodeResponsePb.organizationID', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deletedFlag', full_name='QuickInputCodeResponsePb.deletedFlag', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deleteFlagCH', full_name='QuickInputCodeResponsePb.deleteFlagCH', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='procedureName', full_name='QuickInputCodeResponsePb.procedureName', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='examBodyPartName', full_name='QuickInputCodeResponsePb.examBodyPartName', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observationLocation', full_name='QuickInputCodeResponsePb.observationLocation', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=420,
)

DESCRIPTOR.message_types_by_name['QuickInputCodeResponsePb'] = _QUICKINPUTCODERESPONSEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QuickInputCodeResponsePb = _reflection.GeneratedProtocolMessageType('QuickInputCodeResponsePb', (_message.Message,), {
  'DESCRIPTOR' : _QUICKINPUTCODERESPONSEPB,
  '__module__' : 'QuickInputCodeResponsePb_pb2'
  # @@protoc_insertion_point(class_scope:QuickInputCodeResponsePb)
  })
_sym_db.RegisterMessage(QuickInputCodeResponsePb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
