# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ServiceSectResponsePb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ServiceSectResponsePb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n\x1bServiceSectResponsePb.proto\"\xf5\x01\n\x15ServiceSectResponsePb\x12\x0c\n\x04pKID\x18\x01 \x01(\t\x12\x15\n\rserviceSectID\x18\x02 \x01(\t\x12\x11\n\tinputCode\x18\x03 \x01(\t\x12\x17\n\x0fserviceSectName\x18\x04 \x01(\t\x12\x16\n\x0eserviceSectEng\x18\x05 \x01(\t\x12\x1b\n\x13parentServiceSectID\x18\x06 \x01(\t\x12\x19\n\x11observationDeptID\x18\x07 \x01(\t\x12\x16\n\x0eorganizationID\x18\x08 \x01(\t\x12\x13\n\x0b\x64\x65letedFlag\x18\t \x01(\x08\x12\x0e\n\x06sortNo\x18\n \x01(\x05\x42\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
)




_SERVICESECTRESPONSEPB = _descriptor.Descriptor(
  name='ServiceSectResponsePb',
  full_name='ServiceSectResponsePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pKID', full_name='ServiceSectResponsePb.pKID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serviceSectID', full_name='ServiceSectResponsePb.serviceSectID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inputCode', full_name='ServiceSectResponsePb.inputCode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serviceSectName', full_name='ServiceSectResponsePb.serviceSectName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serviceSectEng', full_name='ServiceSectResponsePb.serviceSectEng', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parentServiceSectID', full_name='ServiceSectResponsePb.parentServiceSectID', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observationDeptID', full_name='ServiceSectResponsePb.observationDeptID', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='organizationID', full_name='ServiceSectResponsePb.organizationID', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deletedFlag', full_name='ServiceSectResponsePb.deletedFlag', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sortNo', full_name='ServiceSectResponsePb.sortNo', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=277,
)

DESCRIPTOR.message_types_by_name['ServiceSectResponsePb'] = _SERVICESECTRESPONSEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServiceSectResponsePb = _reflection.GeneratedProtocolMessageType('ServiceSectResponsePb', (_message.Message,), {
  'DESCRIPTOR' : _SERVICESECTRESPONSEPB,
  '__module__' : 'ServiceSectResponsePb_pb2'
  # @@protoc_insertion_point(class_scope:ServiceSectResponsePb)
  })
_sym_db.RegisterMessage(ServiceSectResponsePb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
