# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WebParamResponsePb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WebParamResponsePb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n\x18WebParamResponsePb.proto\"V\n\x12WebParamResponsePb\x12\x11\n\tparamName\x18\x01 \x01(\t\x12\x12\n\nparamValue\x18\x02 \x01(\t\x12\x19\n\x11linkedServiceType\x18\x03 \x01(\tB\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
)




_WEBPARAMRESPONSEPB = _descriptor.Descriptor(
  name='WebParamResponsePb',
  full_name='WebParamResponsePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='paramName', full_name='WebParamResponsePb.paramName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='paramValue', full_name='WebParamResponsePb.paramValue', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='linkedServiceType', full_name='WebParamResponsePb.linkedServiceType', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=114,
)

DESCRIPTOR.message_types_by_name['WebParamResponsePb'] = _WEBPARAMRESPONSEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WebParamResponsePb = _reflection.GeneratedProtocolMessageType('WebParamResponsePb', (_message.Message,), {
  'DESCRIPTOR' : _WEBPARAMRESPONSEPB,
  '__module__' : 'WebParamResponsePb_pb2'
  # @@protoc_insertion_point(class_scope:WebParamResponsePb)
  })
_sym_db.RegisterMessage(WebParamResponsePb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
