# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CriticalReportRequestPb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CriticalReportRequestPb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n\x1d\x43riticalReportRequestPb.proto\"\xba\x07\n\x17\x43riticalReportRequestPb\x12\x12\n\ncriticalID\x18\x01 \x01(\t\x12\x11\n\tpatientID\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x14\n\x0cpatientPhone\x18\x04 \x01(\t\x12\x14\n\x0c\x63riticalInfo\x18\x05 \x01(\t\x12\x17\n\x0f\x63riticalDispose\x18\x06 \x01(\t\x12\x15\n\rnoticeDocName\x18\x07 \x01(\t\x12\x14\n\x0cnoticeDocTel\x18\x08 \x01(\t\x12\x15\n\rnoticeDocCode\x18\t \x01(\t\x12\x12\n\nnoticeDate\x18\n \x01(\t\x12\x13\n\x0brecordDocID\x18\x0b \x01(\t\x12\x12\n\nrecordDate\x18\x0c \x01(\t\x12\x10\n\x08reportID\x18\r \x01(\t\x12\x19\n\x11observationDeptID\x18\x0e \x01(\t\x12\x16\n\x0eorganizationID\x18\x0f \x01(\t\x12\x1b\n\x13noticeAttendingFlag\x18\x10 \x01(\x08\x12\x19\n\x11\x64isposeFinishFlag\x18\x11 \x01(\x08\x12\x13\n\x0b\x64\x65letedFlag\x18\x12 \x01(\x08\x12\x1a\n\x12replyClinicDocName\x18\x13 \x01(\t\x12\x14\n\x0creplyContent\x18\x14 \x01(\t\x12\x11\n\treplyDate\x18\x15 \x01(\t\x12\x13\n\x0bremindTimes\x18\x16 \x01(\x05\x12\x1a\n\x12timeOutRemindTimes\x18\x17 \x01(\x05\x12\x1b\n\x13\x64isableTimeOutRFlag\x18\x18 \x01(\x08\x12\x15\n\routpatientTel\x18\x19 \x01(\t\x12\x15\n\rprincipalsTel\x18\x1a \x01(\t\x12\x1d\n\x15generalMedicalDutyTel\x18\x1b \x01(\t\x12\x17\n\x0f\x63\x61llPatientFlag\x18\x1c \x01(\x08\x12\x1e\n\x16\x63\x61llOutpatientDeptFlag\x18\x1d \x01(\x08\x12\x14\n\x0c\x63\x61llDutyFlag\x18\x1e \x01(\x08\x12\x14\n\x0csendSucsFlag\x18\x1f \x01(\x08\x12\x11\n\tsendCount\x18  \x01(\x05\x12\x19\n\x11messageForPatient\x18! \x01(\t\x12\x18\n\x10messageForDoctor\x18\" \x01(\t\x12\x1f\n\x17isSendMessageForPatient\x18# \x01(\x08\x12\x1e\n\x16isSendMessageForDoctor\x18$ \x01(\x08\x12\x14\n\x0cresultStatus\x18% \x01(\t\x12\x18\n\x10resultStatusCode\x18& \x01(\t\x12\x14\n\x0c\x63\x61ncelReason\x18\' \x01(\tB\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
)




_CRITICALREPORTREQUESTPB = _descriptor.Descriptor(
  name='CriticalReportRequestPb',
  full_name='CriticalReportRequestPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='criticalID', full_name='CriticalReportRequestPb.criticalID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='patientID', full_name='CriticalReportRequestPb.patientID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='CriticalReportRequestPb.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='patientPhone', full_name='CriticalReportRequestPb.patientPhone', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='criticalInfo', full_name='CriticalReportRequestPb.criticalInfo', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='criticalDispose', full_name='CriticalReportRequestPb.criticalDispose', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='noticeDocName', full_name='CriticalReportRequestPb.noticeDocName', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='noticeDocTel', full_name='CriticalReportRequestPb.noticeDocTel', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='noticeDocCode', full_name='CriticalReportRequestPb.noticeDocCode', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='noticeDate', full_name='CriticalReportRequestPb.noticeDate', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recordDocID', full_name='CriticalReportRequestPb.recordDocID', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recordDate', full_name='CriticalReportRequestPb.recordDate', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reportID', full_name='CriticalReportRequestPb.reportID', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observationDeptID', full_name='CriticalReportRequestPb.observationDeptID', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='organizationID', full_name='CriticalReportRequestPb.organizationID', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='noticeAttendingFlag', full_name='CriticalReportRequestPb.noticeAttendingFlag', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disposeFinishFlag', full_name='CriticalReportRequestPb.disposeFinishFlag', index=16,
      number=17, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deletedFlag', full_name='CriticalReportRequestPb.deletedFlag', index=17,
      number=18, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='replyClinicDocName', full_name='CriticalReportRequestPb.replyClinicDocName', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='replyContent', full_name='CriticalReportRequestPb.replyContent', index=19,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='replyDate', full_name='CriticalReportRequestPb.replyDate', index=20,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remindTimes', full_name='CriticalReportRequestPb.remindTimes', index=21,
      number=22, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeOutRemindTimes', full_name='CriticalReportRequestPb.timeOutRemindTimes', index=22,
      number=23, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disableTimeOutRFlag', full_name='CriticalReportRequestPb.disableTimeOutRFlag', index=23,
      number=24, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outpatientTel', full_name='CriticalReportRequestPb.outpatientTel', index=24,
      number=25, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='principalsTel', full_name='CriticalReportRequestPb.principalsTel', index=25,
      number=26, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='generalMedicalDutyTel', full_name='CriticalReportRequestPb.generalMedicalDutyTel', index=26,
      number=27, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='callPatientFlag', full_name='CriticalReportRequestPb.callPatientFlag', index=27,
      number=28, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='callOutpatientDeptFlag', full_name='CriticalReportRequestPb.callOutpatientDeptFlag', index=28,
      number=29, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='callDutyFlag', full_name='CriticalReportRequestPb.callDutyFlag', index=29,
      number=30, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sendSucsFlag', full_name='CriticalReportRequestPb.sendSucsFlag', index=30,
      number=31, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sendCount', full_name='CriticalReportRequestPb.sendCount', index=31,
      number=32, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='messageForPatient', full_name='CriticalReportRequestPb.messageForPatient', index=32,
      number=33, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='messageForDoctor', full_name='CriticalReportRequestPb.messageForDoctor', index=33,
      number=34, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isSendMessageForPatient', full_name='CriticalReportRequestPb.isSendMessageForPatient', index=34,
      number=35, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isSendMessageForDoctor', full_name='CriticalReportRequestPb.isSendMessageForDoctor', index=35,
      number=36, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resultStatus', full_name='CriticalReportRequestPb.resultStatus', index=36,
      number=37, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resultStatusCode', full_name='CriticalReportRequestPb.resultStatusCode', index=37,
      number=38, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cancelReason', full_name='CriticalReportRequestPb.cancelReason', index=38,
      number=39, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=988,
)

DESCRIPTOR.message_types_by_name['CriticalReportRequestPb'] = _CRITICALREPORTREQUESTPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CriticalReportRequestPb = _reflection.GeneratedProtocolMessageType('CriticalReportRequestPb', (_message.Message,), {
  'DESCRIPTOR' : _CRITICALREPORTREQUESTPB,
  '__module__' : 'CriticalReportRequestPb_pb2'
  # @@protoc_insertion_point(class_scope:CriticalReportRequestPb)
  })
_sym_db.RegisterMessage(CriticalReportRequestPb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
