# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DropDownParamRequestPb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DropDownParamRequestPb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n\x1c\x44ropDownParamRequestPb.proto\"Y\n\x16\x44ropDownParamRequestPb\x12\x16\n\x0eorganizationID\x18\x01 \x03(\t\x12\x19\n\x11observationDeptID\x18\x02 \x03(\t\x12\x0c\n\x04type\x18\x03 \x03(\tB\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
)




_DROPDOWNPARAMREQUESTPB = _descriptor.Descriptor(
  name='DropDownParamRequestPb',
  full_name='DropDownParamRequestPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='organizationID', full_name='DropDownParamRequestPb.organizationID', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observationDeptID', full_name='DropDownParamRequestPb.observationDeptID', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='DropDownParamRequestPb.type', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['DropDownParamRequestPb'] = _DROPDOWNPARAMREQUESTPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DropDownParamRequestPb = _reflection.GeneratedProtocolMessageType('DropDownParamRequestPb', (_message.Message,), {
  'DESCRIPTOR' : _DROPDOWNPARAMREQUESTPB,
  '__module__' : 'DropDownParamRequestPb_pb2'
  # @@protoc_insertion_point(class_scope:DropDownParamRequestPb)
  })
_sym_db.RegisterMessage(DropDownParamRequestPb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
