# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DropDownTreeResponsePb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DropDownTreeResponsePb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n\x1c\x44ropDownTreeResponsePb.proto\"\x99\x01\n\x16\x44ropDownTreeResponsePb\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12)\n\x08\x63hildren\x18\x03 \x03(\x0b\x32\x17.DropDownTreeResponsePb\x12\r\n\x05label\x18\x04 \x01(\t\x12\x0c\n\x04prop\x18\x05 \x01(\t\x12\x0b\n\x03pid\x18\x06 \x01(\t\x12\x10\n\x08rootFlag\x18\x07 \x01(\x08\x42\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
)




_DROPDOWNTREERESPONSEPB = _descriptor.Descriptor(
  name='DropDownTreeResponsePb',
  full_name='DropDownTreeResponsePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='DropDownTreeResponsePb.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='DropDownTreeResponsePb.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='children', full_name='DropDownTreeResponsePb.children', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='DropDownTreeResponsePb.label', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prop', full_name='DropDownTreeResponsePb.prop', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pid', full_name='DropDownTreeResponsePb.pid', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rootFlag', full_name='DropDownTreeResponsePb.rootFlag', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=186,
)

_DROPDOWNTREERESPONSEPB.fields_by_name['children'].message_type = _DROPDOWNTREERESPONSEPB
DESCRIPTOR.message_types_by_name['DropDownTreeResponsePb'] = _DROPDOWNTREERESPONSEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DropDownTreeResponsePb = _reflection.GeneratedProtocolMessageType('DropDownTreeResponsePb', (_message.Message,), {
  'DESCRIPTOR' : _DROPDOWNTREERESPONSEPB,
  '__module__' : 'DropDownTreeResponsePb_pb2'
  # @@protoc_insertion_point(class_scope:DropDownTreeResponsePb)
  })
_sym_db.RegisterMessage(DropDownTreeResponsePb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
