# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KeyWordResponsePb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='KeyWordResponsePb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n\x17KeyWordResponsePb.proto\"\xd5\x01\n\x11KeyWordResponsePb\x12\x11\n\tkeyWordID\x18\x01 \x01(\t\x12\x13\n\x0bkeyWordName\x18\x02 \x01(\t\x12\x13\n\x0bkeyWordCode\x18\x03 \x01(\t\x12\x16\n\x0ekeyDescription\x18\x04 \x01(\t\x12\x0f\n\x07keyType\x18\x05 \x01(\t\x12\x11\n\tkeyTypeCH\x18\x06 \x01(\t\x12\x14\n\x0c\x65xcludeWords\x18\x07 \x01(\t\x12\x19\n\x11observationDeptID\x18\x08 \x01(\t\x12\x16\n\x0eorganizationID\x18\t \x01(\tB\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
)




_KEYWORDRESPONSEPB = _descriptor.Descriptor(
  name='KeyWordResponsePb',
  full_name='KeyWordResponsePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='keyWordID', full_name='KeyWordResponsePb.keyWordID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keyWordName', full_name='KeyWordResponsePb.keyWordName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keyWordCode', full_name='KeyWordResponsePb.keyWordCode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keyDescription', full_name='KeyWordResponsePb.keyDescription', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keyType', full_name='KeyWordResponsePb.keyType', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keyTypeCH', full_name='KeyWordResponsePb.keyTypeCH', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='excludeWords', full_name='KeyWordResponsePb.excludeWords', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observationDeptID', full_name='KeyWordResponsePb.observationDeptID', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='organizationID', full_name='KeyWordResponsePb.organizationID', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=241,
)

DESCRIPTOR.message_types_by_name['KeyWordResponsePb'] = _KEYWORDRESPONSEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KeyWordResponsePb = _reflection.GeneratedProtocolMessageType('KeyWordResponsePb', (_message.Message,), {
  'DESCRIPTOR' : _KEYWORDRESPONSEPB,
  '__module__' : 'KeyWordResponsePb_pb2'
  # @@protoc_insertion_point(class_scope:KeyWordResponsePb)
  })
_sym_db.RegisterMessage(KeyWordResponsePb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
