# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OrderReportRequestPb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import report.proto_pb.ReportRequestPb_pb2 as ReportRequestPb__pb2
import report.proto_pb.MessageRequestPb_pb2 as MessageRequestPb__pb2
import report.proto_pb.ParameterRequestPb_pb2 as ParameterRequestPb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='OrderReportRequestPb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n\x1aOrderReportRequestPb.proto\x1a\x15ReportRequestPb.proto\x1a\x16MessageRequestPb.proto\x1a\x18ParameterRequestPb.proto\"\x86\x01\n\x14OrderReportRequestPb\x12 \n\x06report\x18\x01 \x01(\x0b\x32\x10.ReportRequestPb\x12!\n\x06params\x18\x02 \x03(\x0b\x32\x11.MessageRequestPb\x12)\n\x0csystemParams\x18\x03 \x03(\x0b\x32\x13.ParameterRequestPbB\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
  ,
  dependencies=[ReportRequestPb__pb2.DESCRIPTOR,MessageRequestPb__pb2.DESCRIPTOR,ParameterRequestPb__pb2.DESCRIPTOR,])




_ORDERREPORTREQUESTPB = _descriptor.Descriptor(
  name='OrderReportRequestPb',
  full_name='OrderReportRequestPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='report', full_name='OrderReportRequestPb.report', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='OrderReportRequestPb.params', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='systemParams', full_name='OrderReportRequestPb.systemParams', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=238,
)

_ORDERREPORTREQUESTPB.fields_by_name['report'].message_type = ReportRequestPb__pb2._REPORTREQUESTPB
_ORDERREPORTREQUESTPB.fields_by_name['params'].message_type = MessageRequestPb__pb2._MESSAGEREQUESTPB
_ORDERREPORTREQUESTPB.fields_by_name['systemParams'].message_type = ParameterRequestPb__pb2._PARAMETERREQUESTPB
DESCRIPTOR.message_types_by_name['OrderReportRequestPb'] = _ORDERREPORTREQUESTPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrderReportRequestPb = _reflection.GeneratedProtocolMessageType('OrderReportRequestPb', (_message.Message,), dict(
  DESCRIPTOR = _ORDERREPORTREQUESTPB,
  __module__ = 'OrderReportRequestPb_pb2'
  # @@protoc_insertion_point(class_scope:OrderReportRequestPb)
  ))
_sym_db.RegisterMessage(OrderReportRequestPb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
