# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReportConditionRequestPb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReportConditionRequestPb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n\x1eReportConditionRequestPb.proto\"\xdd\x02\n\x18ReportConditionRequestPb\x12\x14\n\x0cregisterTime\x18\x01 \x01(\t\x12\x0f\n\x07gapTime\x18\x02 \x01(\x05\x12\x15\n\rserviceSectID\x18\x03 \x01(\t\x12\x14\n\x0cpatientClass\x18\x04 \x01(\t\x12\x13\n\x0bpatientType\x18\x05 \x01(\t\x12\x14\n\x0cresultStatus\x18\x06 \x01(\t\x12\x15\n\rprocedureName\x18\x07 \x01(\t\x12\x12\n\ninitiative\x18\x08 \x01(\x08\x12\x0f\n\x07regDate\x18\t \x01(\t\x12\x1a\n\x12observationEndDate\x18\n \x01(\t\x12\x15\n\rqAachieveDate\x18\x0b \x01(\t\x12\x1a\n\x12preliminaryEndDate\x18\x0c \x01(\t\x12\x11\n\tpageIndex\x18\r \x01(\x05\x12\x10\n\x08pageSize\x18\x0e \x01(\x05\x12\x12\n\nqueryParam\x18\x0f \x01(\tB\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
)




_REPORTCONDITIONREQUESTPB = _descriptor.Descriptor(
  name='ReportConditionRequestPb',
  full_name='ReportConditionRequestPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='registerTime', full_name='ReportConditionRequestPb.registerTime', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gapTime', full_name='ReportConditionRequestPb.gapTime', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serviceSectID', full_name='ReportConditionRequestPb.serviceSectID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='patientClass', full_name='ReportConditionRequestPb.patientClass', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='patientType', full_name='ReportConditionRequestPb.patientType', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resultStatus', full_name='ReportConditionRequestPb.resultStatus', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='procedureName', full_name='ReportConditionRequestPb.procedureName', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='initiative', full_name='ReportConditionRequestPb.initiative', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='regDate', full_name='ReportConditionRequestPb.regDate', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observationEndDate', full_name='ReportConditionRequestPb.observationEndDate', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qAachieveDate', full_name='ReportConditionRequestPb.qAachieveDate', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='preliminaryEndDate', full_name='ReportConditionRequestPb.preliminaryEndDate', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageIndex', full_name='ReportConditionRequestPb.pageIndex', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='ReportConditionRequestPb.pageSize', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='queryParam', full_name='ReportConditionRequestPb.queryParam', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=384,
)

DESCRIPTOR.message_types_by_name['ReportConditionRequestPb'] = _REPORTCONDITIONREQUESTPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReportConditionRequestPb = _reflection.GeneratedProtocolMessageType('ReportConditionRequestPb', (_message.Message,), dict(
  DESCRIPTOR = _REPORTCONDITIONREQUESTPB,
  __module__ = 'ReportConditionRequestPb_pb2'
  # @@protoc_insertion_point(class_scope:ReportConditionRequestPb)
  ))
_sym_db.RegisterMessage(ReportConditionRequestPb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
