# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReportTemplateDetailResponsePb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReportTemplateDetailResponsePb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n$ReportTemplateDetailResponsePb.proto\"\xc1\x02\n\x1eReportTemplateDetailResponsePb\x12\x14\n\x0ctempDetailID\x18\x01 \x01(\t\x12\x17\n\x0ftemplateClassID\x18\x02 \x01(\t\x12\x16\n\x0etempDetailName\x18\x03 \x01(\t\x12\x14\n\x0cimageInspect\x18\x04 \x01(\t\x12\x15\n\rimageDiagnose\x18\x05 \x01(\t\x12\x0f\n\x07propose\x18\x06 \x01(\t\x12\x13\n\x0bprivateFlag\x18\x07 \x01(\x08\x12\x14\n\x0c\x61\x62normalFlag\x18\x08 \x01(\t\x12\x0e\n\x06sortNo\x18\t \x01(\x05\x12\x0e\n\x06userID\x18\n \x01(\t\x12\x14\n\x0ctemplateFlag\x18\x0b \x01(\x08\x12\x13\n\x0b\x64\x65letedFlag\x18\x0c \x01(\x08\x12\x10\n\x08linkType\x18\r \x01(\t\x12\x12\n\nLinkItemID\x18\x0e \x01(\tB\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
)




_REPORTTEMPLATEDETAILRESPONSEPB = _descriptor.Descriptor(
  name='ReportTemplateDetailResponsePb',
  full_name='ReportTemplateDetailResponsePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tempDetailID', full_name='ReportTemplateDetailResponsePb.tempDetailID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='templateClassID', full_name='ReportTemplateDetailResponsePb.templateClassID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tempDetailName', full_name='ReportTemplateDetailResponsePb.tempDetailName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imageInspect', full_name='ReportTemplateDetailResponsePb.imageInspect', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imageDiagnose', full_name='ReportTemplateDetailResponsePb.imageDiagnose', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='propose', full_name='ReportTemplateDetailResponsePb.propose', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='privateFlag', full_name='ReportTemplateDetailResponsePb.privateFlag', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='abnormalFlag', full_name='ReportTemplateDetailResponsePb.abnormalFlag', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sortNo', full_name='ReportTemplateDetailResponsePb.sortNo', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userID', full_name='ReportTemplateDetailResponsePb.userID', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='templateFlag', full_name='ReportTemplateDetailResponsePb.templateFlag', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deletedFlag', full_name='ReportTemplateDetailResponsePb.deletedFlag', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='linkType', full_name='ReportTemplateDetailResponsePb.linkType', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='LinkItemID', full_name='ReportTemplateDetailResponsePb.LinkItemID', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=362,
)

DESCRIPTOR.message_types_by_name['ReportTemplateDetailResponsePb'] = _REPORTTEMPLATEDETAILRESPONSEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReportTemplateDetailResponsePb = _reflection.GeneratedProtocolMessageType('ReportTemplateDetailResponsePb', (_message.Message,), dict(
  DESCRIPTOR = _REPORTTEMPLATEDETAILRESPONSEPB,
  __module__ = 'ReportTemplateDetailResponsePb_pb2'
  # @@protoc_insertion_point(class_scope:ReportTemplateDetailResponsePb)
  ))
_sym_db.RegisterMessage(ReportTemplateDetailResponsePb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
