# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ViSpecialCharInfoRequestPb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ViSpecialCharInfoRequestPb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n ViSpecialCharInfoRequestPb.proto\"\xb8\x02\n\x1aViSpecialCharInfoRequestPb\x12\x15\n\rspecialCharID\x18\x01 \x01(\t\x12\x17\n\x0fspecialCharCode\x18\x02 \x01(\t\x12\x13\n\x0bspecialChar\x18\x03 \x01(\t\x12\x19\n\x11observationDeptID\x18\x04 \x01(\t\x12\x16\n\x0eorganizationID\x18\x05 \x01(\t\x12\x0e\n\x06linkID\x18\x06 \x01(\t\x12\x10\n\x08linkType\x18\x07 \x01(\t\x12\x12\n\nlinkItemID\x18\x08 \x01(\t\x12\x1b\n\x13\x62\x65longServiceSectID\x18\t \x01(\t\x12\x18\n\x10\x62\x65longBodypartID\x18\n \x01(\t\x12\x0e\n\x06sortNo\x18\x0b \x01(\x05\x12\x13\n\x0b\x63urrentPage\x18\x0c \x01(\x05\x12\x10\n\x08pageSize\x18\r \x01(\x05\x42\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
)




_VISPECIALCHARINFOREQUESTPB = _descriptor.Descriptor(
  name='ViSpecialCharInfoRequestPb',
  full_name='ViSpecialCharInfoRequestPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='specialCharID', full_name='ViSpecialCharInfoRequestPb.specialCharID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='specialCharCode', full_name='ViSpecialCharInfoRequestPb.specialCharCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='specialChar', full_name='ViSpecialCharInfoRequestPb.specialChar', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observationDeptID', full_name='ViSpecialCharInfoRequestPb.observationDeptID', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='organizationID', full_name='ViSpecialCharInfoRequestPb.organizationID', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='linkID', full_name='ViSpecialCharInfoRequestPb.linkID', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='linkType', full_name='ViSpecialCharInfoRequestPb.linkType', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='linkItemID', full_name='ViSpecialCharInfoRequestPb.linkItemID', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='belongServiceSectID', full_name='ViSpecialCharInfoRequestPb.belongServiceSectID', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='belongBodypartID', full_name='ViSpecialCharInfoRequestPb.belongBodypartID', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sortNo', full_name='ViSpecialCharInfoRequestPb.sortNo', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currentPage', full_name='ViSpecialCharInfoRequestPb.currentPage', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='ViSpecialCharInfoRequestPb.pageSize', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=349,
)

DESCRIPTOR.message_types_by_name['ViSpecialCharInfoRequestPb'] = _VISPECIALCHARINFOREQUESTPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ViSpecialCharInfoRequestPb = _reflection.GeneratedProtocolMessageType('ViSpecialCharInfoRequestPb', (_message.Message,), {
  'DESCRIPTOR' : _VISPECIALCHARINFOREQUESTPB,
  '__module__' : 'ViSpecialCharInfoRequestPb_pb2'
  # @@protoc_insertion_point(class_scope:ViSpecialCharInfoRequestPb)
  })
_sym_db.RegisterMessage(ViSpecialCharInfoRequestPb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
