# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BlockRequestPb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BlockRequestPb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n\x14\x42lockRequestPb.proto\"\x88\x01\n\x0e\x42lockRequestPb\x12\x17\n\x0f\x61\x63\x63\x65ssionNumber\x18\x01 \x01(\t\x12\x11\n\tpatientID\x18\x02 \x01(\t\x12\x17\n\x0fobservationDate\x18\x03 \x01(\t\x12\x1a\n\x12observationEndDate\x18\x04 \x01(\t\x12\x15\n\rserviceSectID\x18\x05 \x01(\tB\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
)




_BLOCKREQUESTPB = _descriptor.Descriptor(
  name='BlockRequestPb',
  full_name='BlockRequestPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accessionNumber', full_name='BlockRequestPb.accessionNumber', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='patientID', full_name='BlockRequestPb.patientID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observationDate', full_name='BlockRequestPb.observationDate', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observationEndDate', full_name='BlockRequestPb.observationEndDate', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serviceSectID', full_name='BlockRequestPb.serviceSectID', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=161,
)

DESCRIPTOR.message_types_by_name['BlockRequestPb'] = _BLOCKREQUESTPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BlockRequestPb = _reflection.GeneratedProtocolMessageType('BlockRequestPb', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKREQUESTPB,
  '__module__' : 'BlockRequestPb_pb2'
  # @@protoc_insertion_point(class_scope:BlockRequestPb)
  })
_sym_db.RegisterMessage(BlockRequestPb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
