# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CompareRequestPb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CompareRequestPb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n\x16\x43ompareRequestPb.proto\"\xd9\x01\n\x10\x43ompareRequestPb\x12\x17\n\x0f\x61\x63\x63\x65ssionNumber\x18\x01 \x01(\t\x12\x11\n\tpatientID\x18\x02 \x01(\t\x12\x17\n\x0fobservationDate\x18\x03 \x01(\t\x12\x1a\n\x12observationEndDate\x18\x04 \x01(\t\x12\x15\n\rserviceSectID\x18\x05 \x01(\t\x12\x15\n\rworkQueueGuid\x18\x06 \x01(\t\x12\x0f\n\x07orderID\x18\x07 \x01(\t\x12\x13\n\x0b\x63urrentPage\x18\x08 \x01(\x05\x12\x10\n\x08pageSize\x18\t \x01(\x05\x42\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
)




_COMPAREREQUESTPB = _descriptor.Descriptor(
  name='CompareRequestPb',
  full_name='CompareRequestPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accessionNumber', full_name='CompareRequestPb.accessionNumber', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='patientID', full_name='CompareRequestPb.patientID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observationDate', full_name='CompareRequestPb.observationDate', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observationEndDate', full_name='CompareRequestPb.observationEndDate', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serviceSectID', full_name='CompareRequestPb.serviceSectID', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workQueueGuid', full_name='CompareRequestPb.workQueueGuid', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orderID', full_name='CompareRequestPb.orderID', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currentPage', full_name='CompareRequestPb.currentPage', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='CompareRequestPb.pageSize', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=244,
)

DESCRIPTOR.message_types_by_name['CompareRequestPb'] = _COMPAREREQUESTPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CompareRequestPb = _reflection.GeneratedProtocolMessageType('CompareRequestPb', (_message.Message,), {
  'DESCRIPTOR' : _COMPAREREQUESTPB,
  '__module__' : 'CompareRequestPb_pb2'
  # @@protoc_insertion_point(class_scope:CompareRequestPb)
  })
_sym_db.RegisterMessage(CompareRequestPb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
