# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExamLoadResponsePb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import techin.proto_pb.OrderResponsePb_pb2 as OrderResponsePb__pb2
import techin.proto_pb.MessageResponsePb_pb2 as MessageResponsePb__pb2
import techin.proto_pb.WorkFlowRemarkResponsePb_pb2 as WorkFlowRemarkResponsePb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ExamLoadResponsePb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n\x18\x45xamLoadResponsePb.proto\x1a\x15OrderResponsePb.proto\x1a\x17MessageResponsePb.proto\x1a\x1eWorkFlowRemarkResponsePb.proto\"\xe8\x01\n\x12\x45xamLoadResponsePb\x12#\n\torderInfo\x18\x01 \x01(\x0b\x32\x10.OrderResponsePb\x12,\n\tworkFlows\x18\x02 \x03(\x0b\x32\x19.WorkFlowRemarkResponsePb\x12 \n\x06images\x18\x03 \x03(\x0b\x32\x10.ImageResponsePb\x12$\n\x08messages\x18\x04 \x03(\x0b\x32\x12.MessageResponsePb\x12\x1e\n\x05units\x18\x05 \x03(\x0b\x32\x0f.UnitResponsePb\x12\x17\n\x0fisAllowedToShow\x18\x06 \x01(\x08\"v\n\x0eUnitResponsePb\x12\x13\n\x0bprocedureID\x18\x01 \x01(\t\x12\x15\n\rprocedureName\x18\x02 \x01(\t\x12\x11\n\tparamName\x18\x03 \x01(\t\x12\x12\n\nparamValue\x18\x04 \x01(\x05\x12\x11\n\tparamUnit\x18\x05 \x01(\t\"6\n\x0fImageResponsePb\x12\x12\n\nimageClass\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\tB\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
  ,
  dependencies=[OrderResponsePb__pb2.DESCRIPTOR,MessageResponsePb__pb2.DESCRIPTOR,WorkFlowRemarkResponsePb__pb2.DESCRIPTOR,])




_EXAMLOADRESPONSEPB = _descriptor.Descriptor(
  name='ExamLoadResponsePb',
  full_name='ExamLoadResponsePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orderInfo', full_name='ExamLoadResponsePb.orderInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workFlows', full_name='ExamLoadResponsePb.workFlows', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='images', full_name='ExamLoadResponsePb.images', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='messages', full_name='ExamLoadResponsePb.messages', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='units', full_name='ExamLoadResponsePb.units', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isAllowedToShow', full_name='ExamLoadResponsePb.isAllowedToShow', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=341,
)


_UNITRESPONSEPB = _descriptor.Descriptor(
  name='UnitResponsePb',
  full_name='UnitResponsePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='procedureID', full_name='UnitResponsePb.procedureID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='procedureName', full_name='UnitResponsePb.procedureName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='paramName', full_name='UnitResponsePb.paramName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='paramValue', full_name='UnitResponsePb.paramValue', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='paramUnit', full_name='UnitResponsePb.paramUnit', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=461,
)


_IMAGERESPONSEPB = _descriptor.Descriptor(
  name='ImageResponsePb',
  full_name='ImageResponsePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageClass', full_name='ImageResponsePb.imageClass', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='ImageResponsePb.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=463,
  serialized_end=517,
)

_EXAMLOADRESPONSEPB.fields_by_name['orderInfo'].message_type = OrderResponsePb__pb2._ORDERRESPONSEPB
_EXAMLOADRESPONSEPB.fields_by_name['workFlows'].message_type = WorkFlowRemarkResponsePb__pb2._WORKFLOWREMARKRESPONSEPB
_EXAMLOADRESPONSEPB.fields_by_name['images'].message_type = _IMAGERESPONSEPB
_EXAMLOADRESPONSEPB.fields_by_name['messages'].message_type = MessageResponsePb__pb2._MESSAGERESPONSEPB
_EXAMLOADRESPONSEPB.fields_by_name['units'].message_type = _UNITRESPONSEPB
DESCRIPTOR.message_types_by_name['ExamLoadResponsePb'] = _EXAMLOADRESPONSEPB
DESCRIPTOR.message_types_by_name['UnitResponsePb'] = _UNITRESPONSEPB
DESCRIPTOR.message_types_by_name['ImageResponsePb'] = _IMAGERESPONSEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExamLoadResponsePb = _reflection.GeneratedProtocolMessageType('ExamLoadResponsePb', (_message.Message,), {
  'DESCRIPTOR' : _EXAMLOADRESPONSEPB,
  '__module__' : 'ExamLoadResponsePb_pb2'
  # @@protoc_insertion_point(class_scope:ExamLoadResponsePb)
  })
_sym_db.RegisterMessage(ExamLoadResponsePb)

UnitResponsePb = _reflection.GeneratedProtocolMessageType('UnitResponsePb', (_message.Message,), {
  'DESCRIPTOR' : _UNITRESPONSEPB,
  '__module__' : 'ExamLoadResponsePb_pb2'
  # @@protoc_insertion_point(class_scope:UnitResponsePb)
  })
_sym_db.RegisterMessage(UnitResponsePb)

ImageResponsePb = _reflection.GeneratedProtocolMessageType('ImageResponsePb', (_message.Message,), {
  'DESCRIPTOR' : _IMAGERESPONSEPB,
  '__module__' : 'ExamLoadResponsePb_pb2'
  # @@protoc_insertion_point(class_scope:ImageResponsePb)
  })
_sym_db.RegisterMessage(ImageResponsePb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
