# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SysSearchDetailRequestPb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SysSearchDetailRequestPb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n\x1eSysSearchDetailRequestPb.proto\"\x9c\x02\n\x18SysSearchDetailRequestPb\x12\x10\n\x08\x64\x65tailID\x18\x01 \x01(\t\x12\x12\n\nsolutionID\x18\x02 \x01(\t\x12\x11\n\tfieldName\x18\x03 \x01(\t\x12\x13\n\x0b\x63ompareSign\x18\x04 \x01(\t\x12\x14\n\x0c\x63ompareValue\x18\x05 \x01(\t\x12\x18\n\x10\x63ompareValueType\x18\x06 \x01(\t\x12\x18\n\x10\x66ieldDisplayName\x18\x07 \x01(\t\x12\x11\n\tfieldType\x18\x08 \x01(\x05\x12\x12\n\ninputStyle\x18\t \x01(\x05\x12\x17\n\x0fmultiSelectFlag\x18\n \x01(\x08\x12\x13\n\x0b\x64icCategory\x18\x0b \x01(\t\x12\x13\n\x0b\x66ieldSortNo\x18\x0c \x01(\x05\x42\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
)




_SYSSEARCHDETAILREQUESTPB = _descriptor.Descriptor(
  name='SysSearchDetailRequestPb',
  full_name='SysSearchDetailRequestPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='detailID', full_name='SysSearchDetailRequestPb.detailID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='solutionID', full_name='SysSearchDetailRequestPb.solutionID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fieldName', full_name='SysSearchDetailRequestPb.fieldName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compareSign', full_name='SysSearchDetailRequestPb.compareSign', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compareValue', full_name='SysSearchDetailRequestPb.compareValue', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compareValueType', full_name='SysSearchDetailRequestPb.compareValueType', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fieldDisplayName', full_name='SysSearchDetailRequestPb.fieldDisplayName', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fieldType', full_name='SysSearchDetailRequestPb.fieldType', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inputStyle', full_name='SysSearchDetailRequestPb.inputStyle', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='multiSelectFlag', full_name='SysSearchDetailRequestPb.multiSelectFlag', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dicCategory', full_name='SysSearchDetailRequestPb.dicCategory', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fieldSortNo', full_name='SysSearchDetailRequestPb.fieldSortNo', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=319,
)

DESCRIPTOR.message_types_by_name['SysSearchDetailRequestPb'] = _SYSSEARCHDETAILREQUESTPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SysSearchDetailRequestPb = _reflection.GeneratedProtocolMessageType('SysSearchDetailRequestPb', (_message.Message,), {
  'DESCRIPTOR' : _SYSSEARCHDETAILREQUESTPB,
  '__module__' : 'SysSearchDetailRequestPb_pb2'
  # @@protoc_insertion_point(class_scope:SysSearchDetailRequestPb)
  })
_sym_db.RegisterMessage(SysSearchDetailRequestPb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
