# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SysSearchSolutionRequestPb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SysSearchSolutionRequestPb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n SysSearchSolutionRequestPb.proto\"\x8b\x03\n\x1aSysSearchSolutionRequestPb\x12\x12\n\nsolutionID\x18\x01 \x01(\t\x12\x14\n\x0csolutionName\x18\x02 \x01(\t\x12\x19\n\x11logicalExpression\x18\x03 \x01(\t\x12\x14\n\x0csolutionType\x18\x04 \x01(\t\x12\x18\n\x10parentSolutionID\x18\x05 \x01(\t\x12\x12\n\nlinkUserID\x18\x06 \x01(\t\x12\x18\n\x10solutionRootFlag\x18\x07 \x01(\x08\x12\x13\n\x0bprivateFlag\x18\x08 \x01(\x08\x12\x13\n\x0b\x64\x65letedFlag\x18\t \x01(\x08\x12\x14\n\x0c\x63reationTime\x18\n \x01(\t\x12\x11\n\tcreaterID\x18\x0b \x01(\t\x12\x12\n\nmodifierID\x18\x0c \x01(\t\x12\x18\n\x10modificationTime\x18\r \x01(\t\x12\x14\n\x0cprivateFlags\x18\x0e \x01(\t\x12\x16\n\x0eorganizationID\x18\x0f \x01(\t\x12\x1b\n\x13solutionDetailClass\x18\x10 \x01(\tB\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
)




_SYSSEARCHSOLUTIONREQUESTPB = _descriptor.Descriptor(
  name='SysSearchSolutionRequestPb',
  full_name='SysSearchSolutionRequestPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='solutionID', full_name='SysSearchSolutionRequestPb.solutionID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='solutionName', full_name='SysSearchSolutionRequestPb.solutionName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='logicalExpression', full_name='SysSearchSolutionRequestPb.logicalExpression', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='solutionType', full_name='SysSearchSolutionRequestPb.solutionType', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parentSolutionID', full_name='SysSearchSolutionRequestPb.parentSolutionID', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='linkUserID', full_name='SysSearchSolutionRequestPb.linkUserID', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='solutionRootFlag', full_name='SysSearchSolutionRequestPb.solutionRootFlag', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='privateFlag', full_name='SysSearchSolutionRequestPb.privateFlag', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deletedFlag', full_name='SysSearchSolutionRequestPb.deletedFlag', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='creationTime', full_name='SysSearchSolutionRequestPb.creationTime', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='createrID', full_name='SysSearchSolutionRequestPb.createrID', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='modifierID', full_name='SysSearchSolutionRequestPb.modifierID', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='modificationTime', full_name='SysSearchSolutionRequestPb.modificationTime', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='privateFlags', full_name='SysSearchSolutionRequestPb.privateFlags', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='organizationID', full_name='SysSearchSolutionRequestPb.organizationID', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='solutionDetailClass', full_name='SysSearchSolutionRequestPb.solutionDetailClass', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=432,
)

DESCRIPTOR.message_types_by_name['SysSearchSolutionRequestPb'] = _SYSSEARCHSOLUTIONREQUESTPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SysSearchSolutionRequestPb = _reflection.GeneratedProtocolMessageType('SysSearchSolutionRequestPb', (_message.Message,), {
  'DESCRIPTOR' : _SYSSEARCHSOLUTIONREQUESTPB,
  '__module__' : 'SysSearchSolutionRequestPb_pb2'
  # @@protoc_insertion_point(class_scope:SysSearchSolutionRequestPb)
  })
_sym_db.RegisterMessage(SysSearchSolutionRequestPb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
