# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ElectronicOrderResponsePb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import register.proto_pb.OrderResponsePb_pb2 as OrderResponsePb__pb2
import register.proto_pb.MessageDataRequestPb_pb2 as MessageDataRequestPb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ElectronicOrderResponsePb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n\x1f\x45lectronicOrderResponsePb.proto\x1a\x15OrderResponsePb.proto\x1a\x1aMessageDataRequestPb.proto\"\x9f\x01\n\x19\x45lectronicOrderResponsePb\x12\x1f\n\x05order\x18\x01 \x03(\x0b\x32\x10.OrderResponsePb\x12\x1c\n\x14isNeedProcessMessage\x18\x02 \x01(\x08\x12\x1b\n\x13isAllowAlterHISInfo\x18\x03 \x01(\x08\x12&\n\x07message\x18\x04 \x03(\x0b\x32\x15.MessageDataRequestPbB\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
  ,
  dependencies=[OrderResponsePb__pb2.DESCRIPTOR,MessageDataRequestPb__pb2.DESCRIPTOR,])




_ELECTRONICORDERRESPONSEPB = _descriptor.Descriptor(
  name='ElectronicOrderResponsePb',
  full_name='ElectronicOrderResponsePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order', full_name='ElectronicOrderResponsePb.order', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isNeedProcessMessage', full_name='ElectronicOrderResponsePb.isNeedProcessMessage', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isAllowAlterHISInfo', full_name='ElectronicOrderResponsePb.isAllowAlterHISInfo', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='ElectronicOrderResponsePb.message', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=246,
)

_ELECTRONICORDERRESPONSEPB.fields_by_name['order'].message_type = OrderResponsePb__pb2._ORDERRESPONSEPB
_ELECTRONICORDERRESPONSEPB.fields_by_name['message'].message_type = MessageDataRequestPb__pb2._MESSAGEDATAREQUESTPB
DESCRIPTOR.message_types_by_name['ElectronicOrderResponsePb'] = _ELECTRONICORDERRESPONSEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ElectronicOrderResponsePb = _reflection.GeneratedProtocolMessageType('ElectronicOrderResponsePb', (_message.Message,), {
  'DESCRIPTOR' : _ELECTRONICORDERRESPONSEPB,
  '__module__' : 'ElectronicOrderResponsePb_pb2'
  # @@protoc_insertion_point(class_scope:ElectronicOrderResponsePb)
  })
_sym_db.RegisterMessage(ElectronicOrderResponsePb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
