# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ElectronicOrderListRequestPb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import register.proto_pb.OrderSearchRequestPb_pb2 as OrderSearchRequestPb__pb2
import register.proto_pb.OrderResponsePb_pb2 as OrderResponsePb__pb2
import register.proto_pb.MessageDataRequestPb_pb2 as MessageDataRequestPb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ElectronicOrderListRequestPb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n\"ElectronicOrderListRequestPb.proto\x1a\x1aOrderSearchRequestPb.proto\x1a\x15OrderResponsePb.proto\x1a\x1aMessageDataRequestPb.proto\"\xaa\x01\n\x1c\x45lectronicOrderListRequestPb\x12\x15\n\rProcessStatus\x18\x01 \x01(\t\x12*\n\x0borderSearch\x18\x02 \x01(\x0b\x32\x15.OrderSearchRequestPb\x12\x1f\n\x05order\x18\x03 \x03(\x0b\x32\x10.OrderResponsePb\x12&\n\x07message\x18\x04 \x03(\x0b\x32\x15.MessageDataRequestPbB\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
  ,
  dependencies=[OrderSearchRequestPb__pb2.DESCRIPTOR,OrderResponsePb__pb2.DESCRIPTOR,MessageDataRequestPb__pb2.DESCRIPTOR,])




_ELECTRONICORDERLISTREQUESTPB = _descriptor.Descriptor(
  name='ElectronicOrderListRequestPb',
  full_name='ElectronicOrderListRequestPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ProcessStatus', full_name='ElectronicOrderListRequestPb.ProcessStatus', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orderSearch', full_name='ElectronicOrderListRequestPb.orderSearch', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order', full_name='ElectronicOrderListRequestPb.order', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='ElectronicOrderListRequestPb.message', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=288,
)

_ELECTRONICORDERLISTREQUESTPB.fields_by_name['orderSearch'].message_type = OrderSearchRequestPb__pb2._ORDERSEARCHREQUESTPB
_ELECTRONICORDERLISTREQUESTPB.fields_by_name['order'].message_type = OrderResponsePb__pb2._ORDERRESPONSEPB
_ELECTRONICORDERLISTREQUESTPB.fields_by_name['message'].message_type = MessageDataRequestPb__pb2._MESSAGEDATAREQUESTPB
DESCRIPTOR.message_types_by_name['ElectronicOrderListRequestPb'] = _ELECTRONICORDERLISTREQUESTPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ElectronicOrderListRequestPb = _reflection.GeneratedProtocolMessageType('ElectronicOrderListRequestPb', (_message.Message,), {
  'DESCRIPTOR' : _ELECTRONICORDERLISTREQUESTPB,
  '__module__' : 'ElectronicOrderListRequestPb_pb2'
  # @@protoc_insertion_point(class_scope:ElectronicOrderListRequestPb)
  })
_sym_db.RegisterMessage(ElectronicOrderListRequestPb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
