# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageDataRequestPb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
import register.proto_pb.ViExamProcedureResponsePb_pb2 as ViExamProcedureResponsePb__pb2
import register.proto_pb.ProcedureResponsePb_pb2 as ProcedureResponsePb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageDataRequestPb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n\x1aMessageDataRequestPb.proto\x1a\x19google/protobuf/any.proto\x1a\x1fViExamProcedureResponsePb.proto\x1a\x19ProcedureResponsePb.proto\"\xea\x02\n\x14MessageDataRequestPb\x12\x11\n\tparamName\x18\x01 \x01(\t\x12\x0f\n\x07\x63\x61ption\x18\x02 \x01(\t\x12\x12\n\nmsgContent\x18\x03 \x01(\t\x12\x15\n\rmsgBoxButtons\x18\x04 \x01(\t\x12\x13\n\x0bmsgBoxIcons\x18\x05 \x01(\t\x12\x11\n\tmsgResult\x18\x06 \x01(\t\x12\x12\n\nisFinished\x18\x07 \x01(\x08\x12\x1a\n\x12isNeedReturnResult\x18\x08 \x01(\x08\x12\x1f\n\x17quietAddProcedureChoose\x18\t \x01(\t\x12\"\n\x04\x64\x61ta\x18\n \x03(\x0b\x32\x14.google.protobuf.Any\x12\x36\n\x12moreMatchProcedure\x18\x0b \x03(\x0b\x32\x1a.ViExamProcedureResponsePb\x12.\n\x10noMatchProcedure\x18\x0c \x03(\x0b\x32\x14.ProcedureResponsePbB\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,ViExamProcedureResponsePb__pb2.DESCRIPTOR,ProcedureResponsePb__pb2.DESCRIPTOR,])




_MESSAGEDATAREQUESTPB = _descriptor.Descriptor(
  name='MessageDataRequestPb',
  full_name='MessageDataRequestPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='paramName', full_name='MessageDataRequestPb.paramName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='caption', full_name='MessageDataRequestPb.caption', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msgContent', full_name='MessageDataRequestPb.msgContent', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msgBoxButtons', full_name='MessageDataRequestPb.msgBoxButtons', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msgBoxIcons', full_name='MessageDataRequestPb.msgBoxIcons', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msgResult', full_name='MessageDataRequestPb.msgResult', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isFinished', full_name='MessageDataRequestPb.isFinished', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isNeedReturnResult', full_name='MessageDataRequestPb.isNeedReturnResult', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quietAddProcedureChoose', full_name='MessageDataRequestPb.quietAddProcedureChoose', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='MessageDataRequestPb.data', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='moreMatchProcedure', full_name='MessageDataRequestPb.moreMatchProcedure', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='noMatchProcedure', full_name='MessageDataRequestPb.noMatchProcedure', index=11,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=480,
)

_MESSAGEDATAREQUESTPB.fields_by_name['data'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_MESSAGEDATAREQUESTPB.fields_by_name['moreMatchProcedure'].message_type = ViExamProcedureResponsePb__pb2._VIEXAMPROCEDURERESPONSEPB
_MESSAGEDATAREQUESTPB.fields_by_name['noMatchProcedure'].message_type = ProcedureResponsePb__pb2._PROCEDURERESPONSEPB
DESCRIPTOR.message_types_by_name['MessageDataRequestPb'] = _MESSAGEDATAREQUESTPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MessageDataRequestPb = _reflection.GeneratedProtocolMessageType('MessageDataRequestPb', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEDATAREQUESTPB,
  '__module__' : 'MessageDataRequestPb_pb2'
  # @@protoc_insertion_point(class_scope:MessageDataRequestPb)
  })
_sym_db.RegisterMessage(MessageDataRequestPb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
