# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OrderStaticListResponsePb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import register.proto_pb.OrderResponsePb_pb2 as OrderResponsePb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='OrderStaticListResponsePb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n\x1fOrderStaticListResponsePb.proto\x1a\x15OrderResponsePb.proto\"h\n\x19OrderStaticListResponsePb\x12\x1e\n\x04list\x18\x01 \x03(\x0b\x32\x10.OrderResponsePb\x12+\n\x0borderStatic\x18\x02 \x01(\x0b\x32\x16.OrderStaticResponsePb\"{\n\x15OrderStaticResponsePb\x12\x1a\n\x12todayRegisterCount\x18\x01 \x01(\x05\x12\x13\n\x0bqueueNumber\x18\x02 \x01(\x05\x12\x19\n\x11shootFinishNumber\x18\x03 \x01(\x05\x12\x16\n\x0eReservedNumber\x18\x04 \x01(\x05\x42\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
  ,
  dependencies=[OrderResponsePb__pb2.DESCRIPTOR,])




_ORDERSTATICLISTRESPONSEPB = _descriptor.Descriptor(
  name='OrderStaticListResponsePb',
  full_name='OrderStaticListResponsePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='list', full_name='OrderStaticListResponsePb.list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orderStatic', full_name='OrderStaticListResponsePb.orderStatic', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=162,
)


_ORDERSTATICRESPONSEPB = _descriptor.Descriptor(
  name='OrderStaticResponsePb',
  full_name='OrderStaticResponsePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='todayRegisterCount', full_name='OrderStaticResponsePb.todayRegisterCount', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='queueNumber', full_name='OrderStaticResponsePb.queueNumber', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shootFinishNumber', full_name='OrderStaticResponsePb.shootFinishNumber', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ReservedNumber', full_name='OrderStaticResponsePb.ReservedNumber', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=287,
)

_ORDERSTATICLISTRESPONSEPB.fields_by_name['list'].message_type = OrderResponsePb__pb2._ORDERRESPONSEPB
_ORDERSTATICLISTRESPONSEPB.fields_by_name['orderStatic'].message_type = _ORDERSTATICRESPONSEPB
DESCRIPTOR.message_types_by_name['OrderStaticListResponsePb'] = _ORDERSTATICLISTRESPONSEPB
DESCRIPTOR.message_types_by_name['OrderStaticResponsePb'] = _ORDERSTATICRESPONSEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrderStaticListResponsePb = _reflection.GeneratedProtocolMessageType('OrderStaticListResponsePb', (_message.Message,), {
  'DESCRIPTOR' : _ORDERSTATICLISTRESPONSEPB,
  '__module__' : 'OrderStaticListResponsePb_pb2'
  # @@protoc_insertion_point(class_scope:OrderStaticListResponsePb)
  })
_sym_db.RegisterMessage(OrderStaticListResponsePb)

OrderStaticResponsePb = _reflection.GeneratedProtocolMessageType('OrderStaticResponsePb', (_message.Message,), {
  'DESCRIPTOR' : _ORDERSTATICRESPONSEPB,
  '__module__' : 'OrderStaticListResponsePb_pb2'
  # @@protoc_insertion_point(class_scope:OrderStaticResponsePb)
  })
_sym_db.RegisterMessage(OrderStaticResponsePb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
