# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProcedureRequestPb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProcedureRequestPb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n\x18ProcedureRequestPb.proto\"\xda\x05\n\x12ProcedureRequestPb\x12\x13\n\x0bprocedureID\x18\x01 \x01(\t\x12\x15\n\rserviceSectID\x18\x02 \x01(\t\x12\x16\n\x0e\x65xamBodyPartID\x18\x03 \x01(\t\x12\x11\n\tinPutCode\x18\x04 \x01(\t\x12\x15\n\rprocedureCode\x18\x05 \x01(\t\x12\x15\n\rprocedureName\x18\x06 \x01(\t\x12\x18\n\x10procedureEngName\x18\x07 \x01(\t\x12\x0f\n\x07hISCode\x18\x08 \x01(\t\x12\x16\n\x0emappingHISCode\x18\t \x01(\t\x12\x14\n\x0c\x65nhancerFlag\x18\n \x01(\x08\x12\x16\n\x0e\x65nhancerFlagCH\x18\x0b \x01(\t\x12\x18\n\x10reprocessingFlag\x18\x0c \x01(\x08\x12\x1a\n\x12reprocessingFlagCH\x18\r \x01(\t\x12\x1f\n\x17\x66ilmSendSelfServiceFlag\x18\x0e \x01(\x08\x12!\n\x19\x66ilmSendSelfServiceFlagCH\x18\x0f \x01(\t\x12\x13\n\x0b\x64\x65letedFlag\x18\x10 \x01(\x08\x12\x15\n\rdeletedFlagCH\x18\x11 \x01(\t\x12\x17\n\x0f\x64iagnoseGroupID\x18\x12 \x01(\t\x12\x17\n\x0fprocedureMethod\x18\x13 \x01(\t\x12\x19\n\x11procedureWorkload\x18\x14 \x01(\x02\x12\x15\n\rprocedureType\x18\x15 \x01(\t\x12\x11\n\tfilmCount\x18\x16 \x01(\x05\x12\x19\n\x11observationDeptID\x18\x17 \x01(\t\x12\x16\n\x0eorganizationID\x18\x18 \x01(\t\x12\x0e\n\x06sortNo\x18\x19 \x01(\x05\x12\x0e\n\x06remark\x18\x1a \x01(\t\x12\x13\n\x0b\x63urrentPage\x18\x1b \x01(\x05\x12\x10\n\x08pageSize\x18\x1c \x01(\x05\x12\x1a\n\x12serviceSectIDArray\x18\x1d \x03(\t\x12\x1b\n\x13\x65xamBodyPartIDArray\x18\x1e \x03(\tB\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
)




_PROCEDUREREQUESTPB = _descriptor.Descriptor(
  name='ProcedureRequestPb',
  full_name='ProcedureRequestPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='procedureID', full_name='ProcedureRequestPb.procedureID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serviceSectID', full_name='ProcedureRequestPb.serviceSectID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='examBodyPartID', full_name='ProcedureRequestPb.examBodyPartID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inPutCode', full_name='ProcedureRequestPb.inPutCode', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='procedureCode', full_name='ProcedureRequestPb.procedureCode', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='procedureName', full_name='ProcedureRequestPb.procedureName', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='procedureEngName', full_name='ProcedureRequestPb.procedureEngName', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hISCode', full_name='ProcedureRequestPb.hISCode', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mappingHISCode', full_name='ProcedureRequestPb.mappingHISCode', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enhancerFlag', full_name='ProcedureRequestPb.enhancerFlag', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enhancerFlagCH', full_name='ProcedureRequestPb.enhancerFlagCH', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reprocessingFlag', full_name='ProcedureRequestPb.reprocessingFlag', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reprocessingFlagCH', full_name='ProcedureRequestPb.reprocessingFlagCH', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filmSendSelfServiceFlag', full_name='ProcedureRequestPb.filmSendSelfServiceFlag', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filmSendSelfServiceFlagCH', full_name='ProcedureRequestPb.filmSendSelfServiceFlagCH', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deletedFlag', full_name='ProcedureRequestPb.deletedFlag', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deletedFlagCH', full_name='ProcedureRequestPb.deletedFlagCH', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='diagnoseGroupID', full_name='ProcedureRequestPb.diagnoseGroupID', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='procedureMethod', full_name='ProcedureRequestPb.procedureMethod', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='procedureWorkload', full_name='ProcedureRequestPb.procedureWorkload', index=19,
      number=20, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='procedureType', full_name='ProcedureRequestPb.procedureType', index=20,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filmCount', full_name='ProcedureRequestPb.filmCount', index=21,
      number=22, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observationDeptID', full_name='ProcedureRequestPb.observationDeptID', index=22,
      number=23, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='organizationID', full_name='ProcedureRequestPb.organizationID', index=23,
      number=24, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sortNo', full_name='ProcedureRequestPb.sortNo', index=24,
      number=25, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remark', full_name='ProcedureRequestPb.remark', index=25,
      number=26, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currentPage', full_name='ProcedureRequestPb.currentPage', index=26,
      number=27, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='ProcedureRequestPb.pageSize', index=27,
      number=28, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serviceSectIDArray', full_name='ProcedureRequestPb.serviceSectIDArray', index=28,
      number=29, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='examBodyPartIDArray', full_name='ProcedureRequestPb.examBodyPartIDArray', index=29,
      number=30, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=759,
)

DESCRIPTOR.message_types_by_name['ProcedureRequestPb'] = _PROCEDUREREQUESTPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProcedureRequestPb = _reflection.GeneratedProtocolMessageType('ProcedureRequestPb', (_message.Message,), {
  'DESCRIPTOR' : _PROCEDUREREQUESTPB,
  '__module__' : 'ProcedureRequestPb_pb2'
  # @@protoc_insertion_point(class_scope:ProcedureRequestPb)
  })
_sym_db.RegisterMessage(ProcedureRequestPb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
