# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SimpleOrderMessageRequestPb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MessageRequestPb_pb2 as MessageRequestPb__pb2
import SimpleOrderRequestPb_pb2 as SimpleOrderRequestPb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SimpleOrderMessageRequestPb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n!SimpleOrderMessageRequestPb.proto\x1a\x16MessageRequestPb.proto\x1a\x1aSimpleOrderRequestPb.proto\"h\n\x1bSimpleOrderMessageRequestPb\x12$\n\x05order\x18\x01 \x01(\x0b\x32\x15.SimpleOrderRequestPb\x12#\n\x08messages\x18\x02 \x03(\x0b\x32\x11.MessageRequestPbB\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
  ,
  dependencies=[MessageRequestPb__pb2.DESCRIPTOR,SimpleOrderRequestPb__pb2.DESCRIPTOR,])




_SIMPLEORDERMESSAGEREQUESTPB = _descriptor.Descriptor(
  name='SimpleOrderMessageRequestPb',
  full_name='SimpleOrderMessageRequestPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order', full_name='SimpleOrderMessageRequestPb.order', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='messages', full_name='SimpleOrderMessageRequestPb.messages', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=193,
)

_SIMPLEORDERMESSAGEREQUESTPB.fields_by_name['order'].message_type = SimpleOrderRequestPb__pb2._SIMPLEORDERREQUESTPB
_SIMPLEORDERMESSAGEREQUESTPB.fields_by_name['messages'].message_type = MessageRequestPb__pb2._MESSAGEREQUESTPB
DESCRIPTOR.message_types_by_name['SimpleOrderMessageRequestPb'] = _SIMPLEORDERMESSAGEREQUESTPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimpleOrderMessageRequestPb = _reflection.GeneratedProtocolMessageType('SimpleOrderMessageRequestPb', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLEORDERMESSAGEREQUESTPB,
  '__module__' : 'SimpleOrderMessageRequestPb_pb2'
  # @@protoc_insertion_point(class_scope:SimpleOrderMessageRequestPb)
  })
_sym_db.RegisterMessage(SimpleOrderMessageRequestPb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
