# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ViExamProcedureTreeResponsePb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import register.proto_pb.ViExamProcedureResponsePb_pb2 as ViExamProcedureResponsePb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ViExamProcedureTreeResponsePb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n#ViExamProcedureTreeResponsePb.proto\x1a\x1fViExamProcedureResponsePb.proto\"\xe9\x01\n\x1dViExamProcedureTreeResponsePb\x12\x16\n\x0e\x65xamBodyPartID\x18\x01 \x01(\x0c\x12\x18\n\x10\x65xamBodyPartCode\x18\x02 \x01(\x0c\x12\x18\n\x10\x65xamBodyPartName\x18\x03 \x01(\x0c\x12\x15\n\rserviceSectID\x18\x04 \x01(\x0c\x12\x32\n\x0e\x65xamProcedures\x18\x05 \x03(\x0b\x32\x1a.ViExamProcedureResponsePb\x12\x31\n\tchildrens\x18\x06 \x03(\x0b\x32\x1e.ViExamProcedureTreeResponsePbB\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
  ,
  dependencies=[ViExamProcedureResponsePb__pb2.DESCRIPTOR,])




_VIEXAMPROCEDURETREERESPONSEPB = _descriptor.Descriptor(
  name='ViExamProcedureTreeResponsePb',
  full_name='ViExamProcedureTreeResponsePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='examBodyPartID', full_name='ViExamProcedureTreeResponsePb.examBodyPartID', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='examBodyPartCode', full_name='ViExamProcedureTreeResponsePb.examBodyPartCode', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='examBodyPartName', full_name='ViExamProcedureTreeResponsePb.examBodyPartName', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serviceSectID', full_name='ViExamProcedureTreeResponsePb.serviceSectID', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='examProcedures', full_name='ViExamProcedureTreeResponsePb.examProcedures', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='childrens', full_name='ViExamProcedureTreeResponsePb.childrens', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=306,
)

_VIEXAMPROCEDURETREERESPONSEPB.fields_by_name['examProcedures'].message_type = ViExamProcedureResponsePb__pb2._VIEXAMPROCEDURERESPONSEPB
_VIEXAMPROCEDURETREERESPONSEPB.fields_by_name['childrens'].message_type = _VIEXAMPROCEDURETREERESPONSEPB
DESCRIPTOR.message_types_by_name['ViExamProcedureTreeResponsePb'] = _VIEXAMPROCEDURETREERESPONSEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ViExamProcedureTreeResponsePb = _reflection.GeneratedProtocolMessageType('ViExamProcedureTreeResponsePb', (_message.Message,), {
  'DESCRIPTOR' : _VIEXAMPROCEDURETREERESPONSEPB,
  '__module__' : 'ViExamProcedureTreeResponsePb_pb2'
  # @@protoc_insertion_point(class_scope:ViExamProcedureTreeResponsePb)
  })
_sym_db.RegisterMessage(ViExamProcedureTreeResponsePb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
